branches:
	only:
		- master
before_install:
	- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script: 
	- make
deploy:
	skip_cleanup: true
	on:
		branch: master
