dist: trusty
branches:
	only:
		- master
before_install:
	- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-full
script: 
	- make
deploy:
	provider: pages
	skip_cleanup: true
	github_token: $GITHUB_TOKEN
	on:
		branch: master
